#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  https://github.com/harisekhon/spotify-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

language: perl
perl:
  - "5.20"
  - "5.10"

sudo: required

notifications:
  email: false

branches:
  only:
    - master

install:
  #- pushd lib
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM LIB FAILED
  #- popd
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM FAILED
  - make

after_success:
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/spotify-tools/trigger/019167ad-6f8e-43c4-9004-7038b5ed077f/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/centos-github/trigger/316d1158-7ffb-49a4-a7bd-8e5456ba2d15/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/ubuntu-github/trigger/abd4dbf0-14bc-454f-9cde-081ec014bc48/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/debian-github/trigger/0cfb3fe7-2028-494b-a43b-068435e6a2b3/
